;; -*- mode: common-lisp; coding: utf-8 -*-
(in-package :hhub)

(defclass OrderShipment (BusinessObject)
  ((row-id)
   (cust-order-id)
   (vendor-order-id)
   (waybill_no)
   (order-date)
   (order-amt)
   (total-discount)
   (name)
   (company-name)
   (addr1)
   (addr2)
   (addr3)
   (pin)
   (city)
   (state)
   (country)
   (phone)
   (alt-phone)
   (email)
   (is-billing-same-as-shipping)
   (billing-name)
   (billing-company)
   (billing-addr1)
   (billing-addr2)
   (billing-addr3)
   (billing-pin)
   (billing-city)
   (billing-country)
   (billing-phone)
   (billing-alt-phone)
   (billing-email)
   (ship-length-cm)
   (ship-width-cm)
   (ship-height-cm)
   (weightkg)
   (shipping-charges)
   (giftwrap-charges)
   (tran-charges)
   (cod-charges)
   (advance-amount)
   (cod-amount)
   (payment-mode)
   (eway-bill-no)
   (return-address-id)
   (pickup-address-id)
   (logistics)
   (order-type)
   (s-type)
   (products)))
  
