invoice_settings:
  invoice_print_settings:
    default_paper_size: A4
    orientation: portrait
    font_size: 12
    margin:
      top: 1cm
      bottom: 1cm
      left: 1cm
      right: 1cm
    header:
      enable: true
      text: "Company Name - Invoice"
      logo_path: "/assets/logo.png"
    footer:
      enable: true
      text: "Thank you for your business!"
    watermark:
      enable: false
      text: ""

  invoice_general_settings:
    invoice_number_format: "INV-YYYY-MM-{counter}"
    default_currency: USD
    date_format: "MM/DD/YYYY"
    time_zone: "America/New_York"
    enable_terms_and_conditions: true
    default_terms_and_conditions: "All sales are final. No refunds."
    enable_discounts: true
    default_discount_rate: 5  # in percentage

  invoice_email_settings:
    send_email_after_generation: true
    email_subject_template: "Your Invoice #{invoice_number}"
    email_body_template: |
      Dear {customer_name},
      
      Please find your invoice attached.
      Thank you for your business!
    cc_email_addresses: []
    attach_invoice_as_pdf: true

  invoice_customer_settings:
    allow_customer_specific_discounts: true
    customer_default_tax_rate: 8.5  # in percentage
    notify_customer_before_due_date: true
    notify_customer_via_whatsapp: true
    default_due_date: "7 days from invoice generation"

  invoice_discounts_and_tax_settings:
    default_discount:
      enable: true
      rate: 10
      description: "Loyalty Discount"
    default_tax:
      enable: true
      tax_rates:
        - name: "Sales Tax"
          rate: 8.5
        - name: "Service Tax"
          rate: 12.0

  invoice_sharing_settings:
    enable_whatsapp_button: true
    enable_live_links: true
    live_link_expiration_days: 30
    qr_code_settings:
      enable: true
      size: 150px
    enable_social_sharing_buttons: true

  live_invoice_settings:
    allow_live_edits: false
    password_protect_links: true
    enable_live_tracking: true
    notify_on_link_access: true

  invoice_pdf_settings:
    optimize_pdf_for_size: true
    add_password_protection: false
    embed_company_logo_in_pdf: true
    pdf_footer_text: "Generated by {company_name} - {date}"

  security_settings:
    allow_invoice_deletion: false
    allow_invoice_edit_after_generation: true
    auto_logout_timer: 30  # in minutes
    two_factor_authentication: true

  advanced_settings:
    enable_custom_scripting: false
    allow_third_party_integrations: true
    webhook_urls:
      - "https://api.example.com/webhook1"
      - "https://api.example.com/webhook2"
    api_keys:
      public_key: "abcd1234"
      private_key: "xyz9876"

  notification_and_alert_settings:
    enable_push_notifications: true
    enable_sms_notifications: true
    sms_template: "Invoice {invoice_number} has been created successfully."
    email_notification_on_payment: true
    reminder_email_template: |
      Hi {customer_name},
      
      This is a friendly reminder that your invoice is due on {due_date}.
      Thank you for your prompt payment.

